config/routes.rb
Rails.application.routes.draw do

  root to: "matches#index"
  resources :users

  resources :matches do
    resources :teams, only: [:edit, :update] do
      member do
        get 'add_member'
      end
      resources :memberships, only: :destroy
    end

    resources :games, only: [ :show, :create ] do
      member do
        get 'add_home'
        get 'add_away'
      end
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :match
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_and_belongs_to_many :teams
  has_many :games

  accepts_nested_attributes_for :teams
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :team
  belongs_to :user
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_and_belongs_to_many :match
  has_many :memberships
  has_many :users, through: :memberships
  validates_presence_of :team_name
  accepts_nested_attributes_for :memberships
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, presence: true
  has_many :memberships
  has_many :teams, through: :memberships

  def display_name
    [first_name, last_name].compact.join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :assign_parents, only: [:show, :add_home, :add_away]
  def show
    @home = Team.find_by(id: @match.home_team_id)
    @away = Team.find_by(id: @match.away_team_id)
  end

  def create
    @match = Match.find(params[:match_id])
    @game = @match.games.create
    redirect_to match_game_path(@match, @game) if @game.save
  end

  def add_home
    @game.increment!(:home_score)
    @home = Team.find_by(id: @match.home_team_id)
    if @game.home_score == 10
      @game.update_attributes(ended: true, winner_id: @home.id, winner_name: @home.team_name)
      redirect_to match_path(@match)
    else
      redirect_to match_game_path(@match, @game)
    end
  end

  def add_away
    @game.increment!(:away_score)
    @away = Team.find_by(id: @match.away_team_id)
    if @game.away_score == 10
      @game.update_attributes(ended: true, winner_id: @away.id, winner_name: @away.team_name)
      redirect_to match_path(@match)
    else
      redirect_to match_game_path(@match, @game)
    end
  end

  def assign_parents
    @match = Match.find(params[:match_id])
    @game = Game.find(params[:id])
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end

  def show
    @match = Match.find(params[:id])
    @home = Team.find(@match.home_team_id)
    @away = Team.find(@match.away_team_id)
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(matches_param)
    @team1 = Team.where(team_name: params[:match][:home_team][:team_name]).first_or_create
    @team2 = Team.where(team_name: params[:match][:away_team][:team_name]).first_or_create
    @match.teams << @team1
    @match.teams << @team2
    @match.home_team_id = @team1.id
    @match.away_team_id = @team2.id
    if @match.save
      redirect_to matches_path
    else
      redirect_to :new
    end
  end

  private

  def matches_param
    params.require(:match).permit(:home_team_id, :away_team_id, teams_attributes: [:team_name])
  end

  def determine_winner

  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def destroy
    @match = Match.find(params[:match_id])
    @team = Team.find(params[:team_id])
    @membership = Membership.find(params[:id])
    if @membership.present?
      @membership.destroy
      redirect_to match_path(@match)
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def add_member
    @match = Match.find(params[:match_id])
    @team = Team.find(params[:id])
  end

  def update
    @match = Match.find(params[:match_id])
    @team = Team.find(params[:id])
    if @team.update_attributes(team_params)
      redirect_to match_path(@match)
    end
  end

  def edit
    @match = Match.find(params[:match_id])
    @team = Team.find(params[:id])
  end

  private

  def team_params
    params.require(:team).permit(:team_name, memberships_attributes: [:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to matches_url, notice: "User Sucessfully created"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/create.html.haml
%h1 Games#create
%p Find me in app/views/games/create.html.haml

app/views/games/show.html.haml
.row
  .col-md-12.game-show
    %h1 GAME
    -if @game.ended?
      %h1 THE ROUND HAS ENDED
      %h2 WINNER: #{@game.winner_name.upcase}
  .col-md-6.game-show
    %h2
      HOME:
    %h1.team-name
      =@home.team_name
    .score
      %h1.score-text
        =@game.home_score
    -if !@game.ended?
      =link_to "+", add_home_match_game_path(@match, @game), class: "btn btn-default"


  .col-md-6.game-show
    %h2
      AWAY
    %h1.team-name
      =@away.team_name
    .score
      %h1.score-text
        =@game.away_score
    -if !@game.ended?
      =link_to "+", add_away_match_game_path(@match, @game), class: "btn btn-default"



%br
  = link_to "Go back to match board", match_path(@match)

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      =link_to "Foosball", root_path, class: "navbar-brand"
    .navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          =link_to "Players", users_path
        %li
          =link_to "View Matches", matches_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FantasyFoosball
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/nav"
    .container
      = yield

app/views/matches/index.html.haml
.navbar.navbar-default
  %ul.navbar-nav.nav
    %li
      =link_to "Start New Match", new_match_path
    %li
      =link_to "Register Players", new_user_path
    %li
      =link_to "View Players", users_path
-@matches.each do |match|
  .match
    %h1
      =link_to "Match ##{match.id}", match_path(match)
      -if match.winner_id.nil?
        %span.label.label-default.label-ongoing On Going

app/views/matches/new.html.haml
.row
  .col-md-10.col-md-offset-1
    %h1 Start a match

    =simple_form_for @match do |f|
      .col-md-4
        =f.simple_fields_for :home_team do |hteam|
          =hteam.input :team_name, label: "Home Team"
      .col-md-4.col-md-offset-2
        =f.simple_fields_for :away_team do |ateam|
          =ateam.input :team_name, label: "Away Team"
      .col-md-10
        =f.button :submit, class: "btn btn-default"

app/views/matches/show.html.haml
.row
  .col-md-12
    %h1 Match ##{@match.id}
  .col-md-6
    %h4
      HOME TEAM
    %h1.team-name
      #{@home.team_name}
      %span.match-rename
        = link_to "Rename", edit_match_team_path(@match, @home.id), class: "label label-default"
    %hr
  .col-md-6
    %h4
      AWAY TEAM
    %h1.team-name
      #{@away.team_name}
      %spam.match-rename
        =link_to "Rename", edit_match_team_path(@match, @away.id), class: "label label-default"
    %hr

.row
  .col-md-6
    %ul
      -@home.memberships.each do |mem|
        %li
          =mem.user.display_name
          %span
            =link_to "Remove Member", match_team_membership_path(@match, @home, mem), method: :delete, class: "label label-warning"
    - if @home.memberships.length < 2
      = link_to "Add players", add_member_match_team_path(@match, @home.id)
    %hr

  .col-md-6
    %ul
      -@away.memberships.each do |mem|
        %li
          =mem.user.display_name
          %span
            =link_to "Remove Member", match_team_membership_path(@match, @home, mem), method: :delete, class: "label label-warning"
    - if @away.memberships.length < 2
      =link_to "Add players", add_member_match_team_path(@match, @away.id)
    %hr

.row
  .col-md-12.match-scoring
    -gameno = 1

    -@match.games.each do |game|
      .each-match.clearfix
        %h2=link_to "GAME ##{gameno}", match_game_path(@match, game)
        -if game.ended?
          %p Game ended with the winner #{game.winner_name}
          .col-md-6
            %h1 #{game.home_score}
          .col-md-6
            %h1 #{game.away_score}
        -else
          %p Game is still going on
        -gameno += 1

    -if @match.games.empty? || @match.games.last.ended?
      = link_to "START A GAME", match_games_path(@match), method: :post, class: "btn btn-default"


    =link_to "Go back to all matches", matches_path, class: "btn btn-default"

app/views/memberships/destroy.html.haml
%h1 Memberships#destroy
%p Find me in app/views/memberships/destroy.html.haml

app/views/users/_form.html.haml
=simple_form_for @user do |f|
  =f.input :first_name
  =f.input :last_name
  =f.button :submit, class: "btn btn-default"

app/views/users/create.html.haml
%h1 New User
=render 'form'

app/views/users/index.html.haml
.row
  .col-md-12.users-index
    =link_to "Add Player", new_user_path, class: "btn btn-default"
    .row
      .col-md-8.col-md-offset-2
        - @users.each do |user|
          %p= user.display_name
          %hr

app/views/users/new.html.haml
.row
  .col-md-5.col-md-offset-3
    %h1 New User
    =render 'form'

app/views/users/show.html.haml
%h1 Users#show
  
%p= @user.first_name
%p= @user.last_name